# packages in environment at c:\Users\leonan.mansano\projeto1\venv:
#
# Name                    Version                   Build  Channel
asgiref                   3.7.2                    pypi_0    pypi
blas                      1.0                         mkl  
bottleneck                1.3.5            py39h080aedc_0  
bzip2                     1.0.8                he774522_0  
ca-certificates           2023.12.12           haa95532_0  
click                     8.1.7           win_pyh7428d3b_0    conda-forge
cmake                     3.26.4               h693b641_0  
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
dj-database-url           2.1.0                    pypi_0    pypi
django                    4.2.9                    pypi_0    pypi
django-heroku             0.3.1                    pypi_0    pypi
django-on-heroku          1.1.2                    pypi_0    pypi
django-wsgi               1.0b1                    pypi_0    pypi
dlib                      19.24.2          py39hb355393_2    conda-forge
exceptiongroup            1.2.0                    pypi_0    pypi
face_recognition          1.3.0              pyhd3deb0d_2    conda-forge
face_recognition_models   0.3.0              pyh9f0ad1d_0    conda-forge
flup                      1.0.3                    pypi_0    pypi
freetype                  2.12.1               hdaf720e_2    conda-forge
gunicorn                  21.2.0                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46320  
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libdeflate                1.19                 hcfcfb64_0    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
libpng                    1.6.39               h8cc25b3_0  
libtiff                   4.6.0                h6e2ebb7_2    conda-forge
libuv                     1.44.2               h2bbff1b_0  
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lz4-c                     1.9.4                h2bbff1b_0  
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mkl                       2023.1.0         h6b88ed4_46358  
mkl-service               2.4.0            py39h2bbff1b_1  
mkl_fft                   1.3.8            py39h2bbff1b_0  
mkl_random                1.2.4            py39h59b6b97_0  
msys2-conda-epoch         20160418                      1    conda-forge
numexpr                   2.8.7            py39h2cd9be0_0  
numpy                     1.26.3           py39h055cbcc_0  
numpy-base                1.26.3           py39h65a83cf_0  
opencv-python             4.9.0.80                 pypi_0    pypi
openjpeg                  2.5.0                h3d672ee_3    conda-forge
openssl                   3.2.0                hcfcfb64_1    conda-forge
packaging                 23.2                     pypi_0    pypi
pandas                    2.1.4            py39h4ed8f06_0  
pillow                    10.2.0           py39h368b509_0    conda-forge
pip                       23.3.1           py39haa95532_0  
pluggy                    1.3.0                    pypi_0    pypi
psycopg2                  2.9.9                    pypi_0    pypi
psycopg2-binary           2.9.9                    pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pytest                    7.4.4                    pypi_0    pypi
python                    3.9.18               h1aa4202_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytz                      2023.3.post1     py39haa95532_0  
setuptools                68.2.2           py39haa95532_0  
six                       1.10.0                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0  
sqlparse                  0.4.4            py39haa95532_0  
tbb                       2021.8.0             h59b6b97_0  
tk                        8.6.13               h5226925_1    conda-forge
tomli                     2.0.1                    pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
tzdata                    2023.4                   pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.2                 h21ff451_1  
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
webob                     1.8.7                    pypi_0    pypi
wheel                     0.41.2           py39haa95532_0  
whitenoise                6.6.0                    pypi_0    pypi
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.4.5                h8cc25b3_0  
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                hd43e919_0  
