# Generated by Django 4.2.9 on 2024-01-18 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('encodings', models.BinaryField(blank=True, null=True)),
                ('total_verificacoes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Verificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(default=datetime.datetime.now)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.pessoa')),
            ],
        ),
    ]
