# Generated by Django 4.2.9 on 2024-01-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_pessoa_encodings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CadastroEmAnalise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("imagem", models.ImageField(upload_to="cadastro_analise/")),
                ("encodings", models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
