# Generated by Django 4.2.9 on 2024-01-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_cadastroemanalise"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastroemanalise",
            name="analise_concluida",
            field=models.BooleanField(default=False),
        ),
    ]
