# Generated by Django 4.2.9 on 2024-01-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_verificacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroReconhecimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horario", models.DateTimeField(auto_now_add=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.pessoa"
                    ),
                ),
            ],
        ),
    ]
